#A very naive piece of code to generate the curl
#Password is generated by using the mOTP app on Android
import urllib2, base64
username = "nhamlevan@gmail.com"
password="711668"
base64string = base64.encodestring('%s:%s' % (username, password))
key = "Basic %s" % base64string

str1='curl -X POST -H "Authorization: '
str2=' " -H "Content-Type: application/json"'
json='{"github_url": "https://github.com/nhamlv-55/hde","contact_email": "nhamlevan@gmail.com"}'
str3= ' -d ' + "'" +json + "' http://hdegip.appspot.com/challenge/001/endpoint"
final_str=str1+key+str2 +str3
print final_str